#!/usr/bin/env python3
"""Validate supply-chain topic JSON files in docs/supply-chain/data/*.json.

Different shape from validate_dd_meta / validate_id_meta:
  - Topics are pure JSON (no HTML wrapper), one file per industry topic
  - Schema: { id, tab, title, subtitle, stats, rows, nodes, edges }
  - Each node has competition (enum) + optional single + companies + sources
  - Each edge is [from_id, to_id]; both ends must be real node ids

Files explicitly NOT validated by this script:
  - topics.json     — registry-shape, different schema
  - dd_links.json   — auto-generated by build_supply_chain_dd_index.py

Usage:
  python scripts/validate_supply_chain_meta.py             # strict: exit 1 on issues
  python scripts/validate_supply_chain_meta.py --report    # exit 0 always
  python scripts/validate_supply_chain_meta.py FILE...     # specific files

Pre-commit hook (scripts/hooks/pre-commit) calls this on staged JSON files.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SC_DATA_DIR = ROOT / "docs" / "supply-chain" / "data"

# Files in data/ that this validator should skip (registry / generated).
SKIP_FILES = {"topics.json", "dd_links.json"}

# Enum whitelists (must match the engine's COMP + FLAG dicts in engine.js).
COMPETITION_VALUES = {"monopoly", "oligopoly", "redocean", "highgrowth", "emerging"}
KIND_VALUES = {"rail", "stage", "demand"}
COUNTRY_VALUES = {
    "TW", "US", "JP", "CN", "KR", "EU", "NL", "DE", "FR", "AT", "SG",
    "IL", "CH", "UK", "HK", "DK", "SE", "GLOBAL",
}

# Stingtao voice residue patterns — these signal source-of-record drift.
# (See SKILL.md Gate G7.)
STINGTAO_RESIDUE = ("本版補齊", "先前漏掉", "設計參考")


def validate_topic(d: dict, filename_stem: str) -> list[str]:
    """Return list of error strings; empty means clean."""
    errs: list[str] = []

    # Top-level required fields
    for k in ("id", "tab", "title", "subtitle", "stats", "rows", "nodes", "edges"):
        if k not in d:
            errs.append(f"missing top-level field '{k}'")

    if errs:
        return errs  # bail early, downstream checks would crash

    # id must match filename
    if d["id"] != filename_stem:
        errs.append(f"id={d['id']!r} does not match filename stem {filename_stem!r}")

    # Stingtao voice residue check on subtitle + analyses
    blob = d.get("subtitle", "") + " ".join(n.get("analysis", "") for n in d["nodes"])
    for pat in STINGTAO_RESIDUE:
        if pat in blob:
            errs.append(
                f"stingtao voice residue: pattern {pat!r} found in subtitle/analysis "
                "(strip third-party voice; see SKILL.md Gate G7)"
            )

    # stats: must be list of 3 cards
    stats = d["stats"]
    if not isinstance(stats, list) or len(stats) != 3:
        errs.append(f"stats: must be list of 3 cards, got {len(stats) if isinstance(stats, list) else type(stats).__name__}")
    else:
        for i, s in enumerate(stats):
            if not isinstance(s, dict):
                errs.append(f"stats[{i}]: must be dict, got {type(s).__name__}")
                continue
            for k in ("k", "v"):
                if k not in s:
                    errs.append(f"stats[{i}]: missing '{k}'")

    # rows: list of dicts with id + label + main
    rows = d["rows"]
    if not isinstance(rows, list) or not rows:
        errs.append("rows: must be non-empty list")
    row_ids: set[str] = set()
    for i, r in enumerate(rows):
        if not isinstance(r, dict):
            errs.append(f"rows[{i}]: must be dict")
            continue
        for k in ("id", "label", "main"):
            if k not in r:
                errs.append(f"rows[{i}]: missing '{k}'")
        if "id" in r:
            row_ids.add(r["id"])

    # nodes: validate structure + collect ids
    nodes = d["nodes"]
    if not isinstance(nodes, list) or not nodes:
        errs.append("nodes: must be non-empty list")
    node_ids: set[str] = set()
    single_count = 0
    golden_count = 0  # ⚑-node × core_business × supply_chain_lock=tight (isGolden in engine.js)
    for i, n in enumerate(nodes):
        if not isinstance(n, dict):
            errs.append(f"nodes[{i}]: must be dict")
            continue
        nid = n.get("id", f"<index {i}>")
        node_ids.add(n.get("id", ""))

        # required scalar fields
        for k in ("id", "row", "col", "span", "kind", "name", "nameEn",
                 "competition", "desc", "growth", "analysis"):
            if k not in n:
                errs.append(f"node {nid}: missing '{k}'")
        if "row" in n and n["row"] not in row_ids:
            errs.append(f"node {nid}: row={n['row']!r} not in rows[]")
        if "competition" in n and n["competition"] not in COMPETITION_VALUES:
            errs.append(
                f"node {nid}: competition={n['competition']!r}; "
                f"allowed {sorted(COMPETITION_VALUES)}"
            )
        if "kind" in n and n["kind"] not in KIND_VALUES:
            errs.append(
                f"node {nid}: kind={n['kind']!r}; allowed {sorted(KIND_VALUES)}"
            )
        if "col" in n and not isinstance(n["col"], int):
            errs.append(f"node {nid}: col must be int, got {type(n['col']).__name__}")
        if "span" in n and not isinstance(n["span"], int):
            errs.append(f"node {nid}: span must be int, got {type(n['span']).__name__}")

        node_has_single = bool(n.get("single"))
        if node_has_single:
            single_count += 1
        # 💎 Top Pick = ⚑ node × core_business × supply_chain_lock==tight
        if node_has_single:
            for c in n.get("companies", []) or []:
                if isinstance(c, dict) and c.get("core_business") is True \
                        and c.get("supply_chain_lock") == "tight":
                    golden_count += 1

        # required list fields
        for k in ("companies", "upstream", "downstream", "sources"):
            if k not in n:
                errs.append(f"node {nid}: missing '{k}'")
                continue
            if not isinstance(n[k], list):
                errs.append(f"node {nid}: '{k}' must be list, got {type(n[k]).__name__}")

        # companies: each must have name + ticker + country + share
        for j, c in enumerate(n.get("companies", []) or []):
            if not isinstance(c, dict):
                errs.append(f"node {nid}.companies[{j}]: must be dict")
                continue
            for k in ("name", "ticker", "country", "share"):
                if k not in c:
                    errs.append(f"node {nid}.companies[{j}]: missing '{k}'")
            ctry = c.get("country")
            if ctry and ctry not in COUNTRY_VALUES:
                errs.append(
                    f"node {nid}.companies[{j}]: country={ctry!r} not in "
                    f"{sorted(COUNTRY_VALUES)}"
                )
            # Golden-intersection optional fields — must be correct type/enum when present
            if "core_business" in c and not isinstance(c["core_business"], bool):
                errs.append(
                    f"node {nid}.companies[{j}]: core_business must be bool, "
                    f"got {type(c['core_business']).__name__}"
                )
            if "growth_trajectory" in c:
                gt = c["growth_trajectory"]
                if gt not in {"high", "med", "low"}:
                    errs.append(
                        f"node {nid}.companies[{j}]: growth_trajectory={gt!r}; "
                        f"allowed ['high', 'med', 'low']"
                    )
            if "supply_chain_lock" in c:
                scl = c["supply_chain_lock"]
                if scl not in {"tight", "med", "loose"}:
                    errs.append(
                        f"node {nid}.companies[{j}]: supply_chain_lock={scl!r}; "
                        f"allowed ['tight', 'med', 'loose']"
                    )
            # Forward-core trajectory (B 例外 — requires 3 hard conditions per SKILL.md)
            if "core_business_trajectory" in c:
                cbt = c["core_business_trajectory"]
                if cbt not in {"high", "med", "low"}:
                    errs.append(
                        f"node {nid}.companies[{j}]: core_business_trajectory={cbt!r}; "
                        f"allowed ['high', 'med', 'low']"
                    )

        # sources: each must have label + url
        for j, s in enumerate(n.get("sources", []) or []):
            if not isinstance(s, dict):
                errs.append(f"node {nid}.sources[{j}]: must be dict")
                continue
            for k in ("label", "url"):
                if k not in s:
                    errs.append(f"node {nid}.sources[{j}]: missing '{k}'")
            url = s.get("url", "")
            if url and not (url.startswith("http://") or url.startswith("https://")):
                errs.append(f"node {nid}.sources[{j}]: url not http(s)://, got {url!r}")

        # require ≥1 source per node (Gate G2)
        if not n.get("sources"):
            errs.append(f"node {nid}: must have ≥1 source (Gate G2 — no '待補')")

        # upstream/downstream id refs must point to real nodes (checked after collecting all ids)

    # edges: each pair must reference real nodes
    edges = d["edges"]
    if not isinstance(edges, list):
        errs.append("edges: must be list")
    for i, e in enumerate(edges or []):
        if not isinstance(e, list) or len(e) != 2:
            errs.append(f"edges[{i}]: must be [from, to] pair, got {e!r}")
            continue
        f, t = e[0], e[1]
        if f not in node_ids:
            errs.append(f"edges[{i}]: 'from' id {f!r} not in nodes[]")
        if t not in node_ids:
            errs.append(f"edges[{i}]: 'to' id {t!r} not in nodes[]")

    # upstream/downstream id refs (second pass with full node_ids set)
    for n in nodes:
        nid = n.get("id", "?")
        for kind in ("upstream", "downstream"):
            for j, ref in enumerate(n.get(kind, []) or []):
                rid = ref.get("id") if isinstance(ref, dict) else ref
                if rid and rid not in node_ids:
                    errs.append(
                        f"node {nid}.{kind}[{j}]: id={rid!r} not in nodes[]"
                    )

    # stats[2].v (single count) must equal actual count
    if isinstance(stats, list) and len(stats) >= 3 and isinstance(stats[2], dict):
        declared = stats[2].get("v")
        if isinstance(declared, int) and declared != single_count:
            errs.append(
                f"stats[2].v={declared} but {single_count} nodes have 'single' field — "
                "update stats card or fix node flags"
            )

    # v1.3 hard caps (⚑ budget + 💎 cap). Only enforced when the topic opts in
    # via `single_point_framework: "v1.3"` — lets the 25 un-migrated maps pass
    # until they are re-graded under the dual-axis + critic framework.
    if d.get("single_point_framework") == "v1.3" and isinstance(nodes, list):
        budget = max(5, math.ceil(len(nodes) * 0.15))
        if single_count > budget:
            errs.append(
                f"v1.3 ⚑ budget: {single_count} single-points exceed per-topic cap "
                f"{budget} (= max(5, ceil({len(nodes)} nodes × 0.15)) — rank by "
                "non-substitutability and demote overflow to main-table notes"
            )
        if golden_count > 5:
            errs.append(
                f"v1.3 💎 cap: {golden_count} Top Picks exceed cap 5 — tighten "
                "core_business / supply_chain_lock (≥2 signals) or rank to top 3-5"
            )

    return errs


def validate_topics_manifest(path: Path) -> list[str]:
    """Light validation for topics.json registry shape."""
    errs: list[str] = []
    try:
        d = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        return [f"topics.json: JSON parse error: {e}"]
    if "topics" not in d or not isinstance(d["topics"], list):
        return ["topics.json: missing or non-list 'topics'"]
    for i, t in enumerate(d["topics"]):
        for k in ("id", "tab", "title", "active"):
            if k not in t:
                errs.append(f"topics[{i}]: missing '{k}'")
        if "active" in t and not isinstance(t["active"], bool):
            errs.append(f"topics[{i}]: active must be bool")
    return errs


def validate_file(path: Path) -> dict:
    if path.name == "topics.json":
        errs = validate_topics_manifest(path)
        return {"status": "invalid" if errs else "ok", "errors": errs, "topic": "registry"}
    if path.name == "dd_links.json":
        return {"status": "skipped_generated", "topic": path.stem}

    try:
        d = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        return {"status": "parse_error", "errors": [f"JSON parse error: {e}"]}

    errs = validate_topic(d, path.stem)
    if errs:
        return {"status": "invalid", "errors": errs, "topic": d.get("id", path.stem)}
    return {"status": "ok", "topic": d.get("id", path.stem)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("files", nargs="*")
    parser.add_argument("--report", action="store_true", help="exit 0 always")
    args = parser.parse_args()

    if args.files:
        targets = [Path(p) for p in args.files]
    else:
        targets = sorted(SC_DATA_DIR.glob("*.json"))

    results = [{"file": p.name, **validate_file(p)} for p in targets]

    print(f"Scanned {len(results)} supply-chain data file(s):")
    counts = {"ok": 0, "invalid": 0, "parse_error": 0, "skipped_generated": 0}
    for r in results:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    print(f"  ✅ ok                 : {counts['ok']}")
    print(f"  ❌ invalid            : {counts['invalid']}")
    print(f"  ❌ JSON parse error   : {counts['parse_error']}")
    print(f"  ↪  skipped (generated): {counts['skipped_generated']}")

    bad = [r for r in results if r["status"] in ("invalid", "parse_error")]
    if bad:
        print()
        for r in bad:
            topic = r.get("topic", "?")
            print(f"[{r['status'].upper()}] {r['file']} (topic={topic})")
            for e in r.get("errors", []):
                print(f"    - {e}")

    return 0 if (args.report or not bad) else 1


if __name__ == "__main__":
    sys.exit(main())
